### ISSUE TITLE
Thanx a lot!

### ISSUE THREAD

**Issue by boretom** [stevekerrison/mongo-qemu-avx#1]
Just a quick "Thank you", I was able to run Graylog on my N5105 based CPU with it.
Not fast but after a few minutes of start up it is usable.

/Thomas

**Comment by stevekerrison** [comment]
[Hooray I'm useful!](https://www.youtube.com/watch?v=S65ZzffW-Cw)

**Comment by fermulator** [comment]
+1 - super awesome idea and elegant implementation

(fwiw) here's how I built and invoked
```
docker build --add-host=deb.debian.org:151.101.194.132 -t mongo-qemu:latest --build-arg mongo_tag=7.0.16 .
```
* host had to be set as my docker system's default DNS apparently is broken for docker build sequences on my docker runner
* specified v7.0.16 (pinned)

then retagged directly
```
$ docker tag mongo-qemu:latest mongo-qemu:7.0.16
$ docker images | grep mongo
mongo-qemu                             7.0.16    4cbfbbaaf20b   19 minutes ago   1.1GB
mongo-qemu                             latest    4cbfbbaaf20b   19 minutes ago   1.1GB
```

and the docker compose to get bootstrapped
```
$ cat docker-compose.yml 
---
version: "3"
services:
  mongodb:
    image: mongo-qemu:7.0.16 
    pull_policy: if_not_present
    container_name: mongodb
    volumes:
      - /mnt/unifi/db:/data/db
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=<foopassword>
    logging:
        options:
            max-size: 1g
    network_mode: "host"
    dns:
      - <piphole IP>
    restart: unless-stopped
```
(my mount point is a bit of a hack for now ... i don't have a generic volume ready for mongo so going to just shove it into unifi's docker mount point as that's why I'm doing all of this anyway ...) https://github.com/linuxserver/docker-unifi-network-application

**Comment by stevekerrison** [comment]
> +1 - super awesome idea and elegant implementation
> [...]
>  i don't have a generic volume ready for mongo so going to just shove it into unifi's docker mount point as that's why I'm doing all of this anyway ...) https://github.com/linuxserver/docker-unifi-network-application

Thanks! I'm grateful to hear from people it's been useful for. I am also using it as the drop-in replacement for MongoDB on my Linuxserver Unifi application. Previously I'd [tried](https://github.com/linuxserver/docker-unifi-network-application/issues/56) using FerretDB, which is middlware between Mongo's wire protocol and a regular old postgres/sqlite DB, but it is messy and unreliable compare to this.
